blank_issues_enabled: true
contact_links:
  - name: Ask a question about Kindling or get support
    url: https://github.com/Kindling-project/kindling/discussions/new
    about: Ask a question or request support for using Kindling
