apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kindling-agent
  name: kindling
  namespace: kindling
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: kindling-agent
  sessionAffinity: None
  type: ClusterIP