# This is a basic workflow to help you get started with Actions

name: Kindling-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #branches: [release-*]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildgrafana:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      RELEASE: ${{ github.event.release.name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup-docker
        # You may pin to the exact commit or the version.
        # uses: docker-practice/actions-setup-docker@9fafeb38361d5d48e5afc207293715e023b6cfe0
        uses: docker-practice/actions-setup-docker@1.0.9

      - name: version
        run: echo "version=latest-alpha" >> $GITHUB_ENV

      - name: get release version
        if: ${{startsWith(github.ref.name,'release-')}}
        run: name=`echo ${{github.ref.name}}`; echo version=${name#*release-} >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: grafana-plugins
          file: docker/Dockerfile
          push: true
          tags: kindlingproject/kindling-grafana:${{env.version}}